Vagrant.configure("2") do |config|
#config.vm.box = "dummy"

config.vm.define "maquina_bot" do |maquina_bot|
    maquina_bot.vm.box = "dummy"

maquina_bot.vm.provider :aws do |aws, override|
aws.access_key_id = ENV['AWS_KEY']
aws.secret_access_key = ENV['AWS_SECRET']
aws.keypair_name = ENV['AWS_KEYNAME']


aws.tags = {
		'Name' => 'Tripbot Bot',
		'Environment' => 'vagrant-sandbox'
    } 
    
    aws.region = "us-east-1"
    aws.ami = "ami-b3123fa4"

    aws.instance_type = "t2.micro"
    aws.security_groups = ["launch-wizard-1"]


override.ssh.username = "ubuntu"
override.ssh.private_key_path = ENV['AWS_KEYPATH']
end

maquina_bot.vm.provision :ansible do |ansible|
ansible.playbook = "Playbooks/playbook_bot.yml"
end
end


    

config.vm.define "maquina_excursiones_y_rutas" do |maquina_excursiones_y_rutas|
    maquina_excursiones_y_rutas.vm.box = "dummy"

maquina_excursiones_y_rutas.vm.provider :aws do |aws, override|
aws.access_key_id = ENV['AWS_KEY']
aws.secret_access_key = ENV['AWS_SECRET']
aws.keypair_name = ENV['AWS_KEYNAME']


aws.tags = {
		'Name' => 'Tripbot Excursiones y Rutas',
		'Environment' => 'vagrant-sandbox'
    } 
    
    aws.region = "us-east-1"
    aws.ami = "ami-b3123fa4"
    aws.instance_type = "t2.micro"
    aws.security_groups = ["launch-wizard-1"]


override.ssh.username = "ubuntu"
override.ssh.private_key_path = ENV['AWS_KEYPATH']
end


maquina_excursiones_y_rutas.vm.provision :ansible do |ansible|
ansible.playbook = "Playbooks/playbook_rutas.yml

end
end




config.vm.define "maquina_inventario_y_equipamiento" do |maquina_inventario_y_equipamiento|
    maquina_inventario_y_equipamiento.vm.box = "dummy"

maquina_inventario_y_equipamiento.vm.provider :aws do |aws, override|
aws.access_key_id = ENV['AWS_KEY']
aws.secret_access_key = ENV['AWS_SECRET']
aws.keypair_name = ENV['AWS_KEYNAME']


aws.tags = {
		'Name' => 'Tripbot Inventario y equipamiento',
		'Environment' => 'vagrant-sandbox'
    } 
    
    aws.region = "us-east-1"
    aws.ami = "ami-b3123fa4"
    aws.instance_type = "t2.micro"
    aws.security_groups = ["launch-wizard-1"]


override.ssh.username = "ubuntu"
override.ssh.private_key_path = ENV['AWS_KEYPATH']
end


maquina_inventario_y_equipamiento.vm.provision :ansible do |ansible|
ansible.playbook = "Playbooks/playbook_equipamiento.yml

end
end




end

