- hosts: all
  sudo: true
  tasks:
    - name: Actualizamos
      apt: update_cache=yes
    - name: Instalamos los paquetes extra de imágenes
      apt: name=linux-image-extra-4.4.0-53-generic
      apt: name=linux-image-extra-virtual
    - name: Instalacion curl
      apt: name=curl
    - name: Instalacion certificados apt https
      apt: name=apt-transport-https
      apt: name=ca-certificates
    - name: Clave de docker
      shell: curl -fsSL https://yum.dockerproject.org/gpg | apt-key add -
    - name: Agregar repositorio estable
      shell: add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-xenial  main"
    - name: Actualizar cache
      apt: update_cache=yes
    - name: Creamos usuario con contraseña y acceso sudo
      user: name=user shell=/bin/bash group=admin password=$6$iTc8Gj93cTvKX$T7l9rxN5ZnphhjxdjI9uYzrkXjfG9qv.ppwvAdPtohRWMn9BtOzhndmDcdiG8EnMVtgnorQrh39yNSdsmwYiS1
    - name: Descarga del contenedor
      shell: docker pull cesar2/tripbot
